env:
  browser: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  indent:
    - warn
    - 4
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  no-unused-vars:
    - error
    - argsIgnorePattern: ^_.+
